apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-180"
  name: argocd-rbac
  namespace: argocd
 
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default 
  syncPolicy:
   automated: {}
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan
    - ServerSideApply=true
  source:
    path: 'argocd-rbac'
    repoURL: '{{ .Values.spec.source.repoURL }}'
