apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-350"
  name: cilium-extra
  namespace: argocd
 
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
   automated: {}
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan
    - ServerSideApply=true
  source:
    path: 'cilium-extra'
    repoURL: '{{ .Values.spec.source.repoURL }}'
