apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-160"
  name: {{ .Values.spec.env }}-confluecnce
  namespace: argocd
spec:
  destination:
    namespace: confluecnce
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  syncPolicy:
   automated: {}
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan
    - ServerSideApply=true
  sources:                       
  - repoURL: "https://stakater.github.io/stakater-charts"
    chart: configmap
    targetRevision: 1.0.5
    helm:
      values: |
         ConfigMap:
          - name: confluence-config
            data:
              server.xml: |
                   <?xml version="1.0" encoding="utf-8"?>
                   <Server port="8000" shutdown="SHUTDOWN">
                       <Service name="Tomcat-Standalone">
                           <!--
                            ==============================================================================================================
                            DEFAULT - Direct connector with no proxy, for unproxied HTTP access to Confluence.
                   
                            If using a http/https proxy, comment out this connector.
                            ==============================================================================================================
                           -->
                           <!--
                           <Connector port="8090" connectionTimeout="20000" redirectPort="8443"
                                      maxThreads="48" maxPostSize="16777216" minSpareThreads="10"
                                      enableLookups="false" acceptCount="10" URIEncoding="UTF-8"
                                      protocol="org.apache.coyote.http11.Http11NioProtocol"/>
                            -->           
                           <!--
                            ==============================================================================================================
                            HTTP - Proxying Confluence via Apache or Nginx over HTTP
                   
                            If you're proxying traffic to Confluence over HTTP, uncomment the connector below and comment out the others.
                            Make sure you provide the right information for proxyName and proxyPort.
                   
                            For more information see:
                               Apache - https://confluence.atlassian.com/x/4xQLM
                               nginx  - https://confluence.atlassian.com/x/TgSvEg
                   
                            ==============================================================================================================
                           -->
                   
                           <!--
                           <Connector port="8090" connectionTimeout="20000" redirectPort="8443"
                                      maxThreads="48" maxPostSize="16777216" minSpareThreads="10"
                                      enableLookups="false" acceptCount="10" URIEncoding="UTF-8"
                                      protocol="org.apache.coyote.http11.Http11NioProtocol"
                                      scheme="http" proxyName="<subdomain>.<domain>.com" proxyPort="80"/>
                           -->
                   
                           <!--
                            ==============================================================================================================
                            HTTPS - Direct connector with no proxy, for unproxied HTTPS access to Confluence.
                   
                            For more info see https://confluence.atlassian.com/x/s3UC
                            ==============================================================================================================
                           -->
                   
                           <!--
                           <Connector port="8443" maxHttpHeaderSize="8192"
                                      maxThreads="150" maxPostSize="16777216" minSpareThreads="25"
                                      protocol="org.apache.coyote.http11.Http11Nio2Protocol"
                                      enableLookups="false" disableUploadTimeout="true"
                                      acceptCount="100" scheme="https" secure="true"
                                      clientAuth="false" sslProtocol="TLSv1.2" sslEnabledProtocols="TLSv1.2" SSLEnabled="true"
                                      URIEncoding="UTF-8" keystorePass="<MY_CERTIFICATE_PASSWORD>"/>
                           -->
                   
                           <!--
                            ==============================================================================================================
                            HTTPS - Proxying Confluence via Apache or Nginx over HTTPS
                   
                            If you're proxying traffic to Confluence over HTTPS, uncomment the connector below and comment out the others.
                            Make sure you provide the right information for proxyName and proxyPort.
                   
                            For more information see:
                               Apache - https://confluence.atlassian.com/x/PTT3MQ
                               nginx  - https://confluence.atlassian.com/x/cNIvMw
                            ==============================================================================================================
                           -->
                   
                           
                           <Connector port="8090" connectionTimeout="20000" redirectPort="8443"
                                      maxThreads="48" maxPostSize="16777216" minSpareThreads="10"
                                      enableLookups="false" acceptCount="10" URIEncoding="UTF-8"
                                      protocol="org.apache.coyote.http11.Http11NioProtocol"
                                      scheme="https" secure="true" proxyName="docs.rimci.dev" proxyPort="443"/>
                           
                   
                           <Engine name="Standalone" defaultHost="localhost">
                               <Host name="localhost" appBase="webapps" unpackWARs="true" autoDeploy="false" startStopThreads="4">
                                   <Context path="" docBase="../confluence" reloadable="false" useHttpOnly="true">
                                       <!-- Logging configuration for Confluence is specified in confluence/WEB-INF/classes/log4j.properties -->
                                       <Manager pathname=""/>
                                       <Valve className="org.apache.catalina.valves.StuckThreadDetectionValve" threshold="60"/>
                   
                                       <!-- http://tomcat.apache.org/tomcat-9.0-doc/config/valve.html#Access_Log_Valve -->
                                       <Valve className="org.apache.catalina.valves.AccessLogValve"
                                              directory="logs"
                                              maxDays="30"
                                              pattern="%t %{X-AUSERNAME}o %I %h %r %s %Dms %b %{Referer}i %{User-Agent}i"
                                              prefix="conf_access_log"
                                              requestAttributesEnabled="true"
                                              rotatable="true"
                                              suffix=".log"
                                       />
                   
                                       <!-- http://tomcat.apache.org/tomcat-9.0-doc/config/valve.html#Remote_IP_Valve -->
                                       <Valve className="org.apache.catalina.valves.RemoteIpValve" />
                                   </Context>
                   
                                   <Context path="${confluence.context.path}/synchrony-proxy" docBase="../synchrony-proxy"
                                            reloadable="false" useHttpOnly="true">
                                       <Valve className="org.apache.catalina.valves.StuckThreadDetectionValve" threshold="60"/>
                                   </Context>
                               </Host>
                           </Engine>
                       </Service>
                   </Server>



  - repoURL: '{{ .Values.spec.source.helmURL }}'
    targetRevision: 13.2.12
    chart: app
    helm:
      values: |-
        global:
          imageRegistry: "{{ .Values.spec.registry }}/"
          storageClass: "k8s-lvm-sc"
        image:
           repository: haxqer/confluence
           tag: 9.5.3
        updateStrategy:
           type: RollingUpdate  
           rollingUpdate:
             maxSurge: 25%
             maxUnavailable: 100%              
        containerPorts:
          http: 8090
        containerSecurityContext:
            enabled: true
            seLinuxOptions: {}
            privileged: true
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
        readinessProbe:
          enabled: false
        livenessProbe:
          enabled: false              
        extraEnvVars:
           - name: JVM_MINIMUM_MEMORY
             value: 4g
           - name: JVM_MAXIMUM_MEMORY
             value: 4g
           - name: CATALINA_CONNECTOR_SCHEME
             value: "https"
           - name: CATALINA_CONNECTOR_SECURE
             value: "true"             
           - name: CATALINA_OPTS
             value: "-Dupm.plugin.upload.enabled=true"              
        #   - name: JVM_CODE_CACHE_ARGS
        #     value: '-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=1g' 
        persistence:
          enabled: true  
          size: 10Gi
          mountPath: /var/confluence
        service:
          type: ClusterIP
          ports:
            http: 8090
        ingress:
           enabled: true
           hostname: docs.rimci.dev
           annotations:
              nginx.ingress.kubernetes.io/proxy-body-size: 200m
              nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
              nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
              nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"  
              nginx.ingress.kubernetes.io/rewrite-target: /
              nginx.ingress.kubernetes.io/configuration-snippet: |
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;           
           ingressClassName: public    
           tls: true
        resources:
          requests:
            cpu: 4
            memory: 8Gi
          limits:
            cpu: 4
            memory: 8Gi  
        extraVolumes:
            - name: confluence-config
              configMap:
                name: confluence-config
        extraVolumeMounts: 
            - name: confluence-config
              mountPath: /opt/confluence/conf/server.xml
              subPath: server.xml              
  - repoURL: 'https://cloudnative-pg.io/charts'
    targetRevision: 0.0.8
    chart: cluster
    helm:
      values: |-
        cluster:
          instances: 2
          annotations:
            cnpg.io/skipWalArchiving: "enabled"
          imageName: {{ .Values.spec.registry }}/cloudnative-pg/postgresql:16.1
          logLevel: warning
          storage:
            size: 5Gi
            storageClass: "k8s-lvm-sc"
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          initdb:
            database: confluecnce
        backups:
          enabled: false
################## backup ###################
  - repoURL: 'https://stakater.github.io/stakater-charts'
    targetRevision: 1.0.5
    chart: secrets
    helm:
      values: |-
         Secrets:
         - name: restic-config
           data:
               RESTIC_REPOSITORY: s3:http://makhzan.rimci.dev:9000/backup/confluecnce/files
               RESTIC_PASSWORD: my-secure-restic-password
               AWS_ACCESS_KEY_ID: backup
               AWS_SECRET_ACCESS_KEY: A7<KbbhD:r35gFr25<yO5#
           type: Opaque          
  - repoURL: '{{ .Values.spec.source.helmURL }}'
    targetRevision: 0.1.0
    chart: 	extra-objects
    helm:
      values: |-
          extraObjects:
            - apiVersion: volsync.backube/v1alpha1
              kind: ReplicationSource
              metadata:
                name: confluecnce-files-backup
              spec:
                sourcePVC: tools-confluecnce-app-app
                trigger:
                  schedule: "0 */6 * * *"
                restic:
                  pruneIntervalDays: 14
                  repository: restic-config
                  retain:
                    hourly: 0
                    daily: 14
                    weekly: 0
                    monthly: 0
                    yearly: 0
                  copyMethod: Direct
                  storageClassName: k8s-lvm-sc

  - repoURL: '{{ .Values.spec.source.helmURL }}'
    targetRevision: "13.2.12"
    chart: app
    helm:
      values: |-
          fullnameOverride: postgresbackup
          global:
            imageRegistry: {{ .Values.spec.registry }}/
          image:
             repository: eeshugerman/postgres-backup-s3
             tag: 16
          extraEnvVars:
            - name: S3_ENDPOINT
              value: http://makhzan.rimci.dev:9000
            - name: SCHEDULE
              value: '0 0 */6 * * *'
            - name: BACKUP_KEEP_DAYS
              value: "15"
            - name: S3_REGION
              value: "minio"
            - name: S3_ACCESS_KEY_ID
              value: "7Xsu50XzoQi91dLWCBQu2UOrb7ly9poh"
            - name: S3_SECRET_ACCESS_KEY
              value: "ZzbddQQSgDHrxWscxLI7PsLNTKoX4Wty"
            - name: S3_BUCKET
              value: "backup"
            - name: S3_PREFIX
              value: "confluecnce/db"
            - name: POSTGRES_HOST
              valueFrom:
               secretKeyRef:
                 name: tools-confluecnce-cluster-superuser
                 key: host
            - name: POSTGRES_DATABASE
              value: confluecnce
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tools-confluecnce-cluster-superuser
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tools-confluecnce-cluster-superuser
                  key: password           
          livenessProbe:
            enabled: false
          readinessProbe:
            enabled: false  
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 500Mi                                
          service:
            type: ClusterIP
