apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-160"
  name: {{ .Values.spec.env }}-keycloakx
  namespace: argocd
spec:
  destination:
    namespace: keycloakx
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  syncPolicy:
   automated: {}
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan
    - ServerSideApply=true
    - Validate=false
  sources:  
                       
  - repoURL: 'https://codecentric.github.io/helm-charts'
    targetRevision: 2.6.0
    chart: keycloakx
    helm:
      values: |-
        image:
           repository: {{ .Values.spec.registry }}/keycloak/keycloak
        command:
          - "/opt/keycloak/bin/kc.sh"
          - "start"
          - "--http-port=8080"
          - "--hostname-strict=false"
        extraEnv: |
          #- name: KC_LOG_LEVEL
          #  value: DEBUG       
          - name: KEYCLOAK_ADMIN
            value: admin
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: o0buRxsxesPeVxWRRVJd7nTirSI52s
          - name: JAVA_OPTS_APPEND
            value: >-
              -Djgroups.dns.query={{ "{{" }} include "keycloak.fullname" . {{ "}}" }}-headless           
          - name: KC_DB
            value: postgres
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tools-keycloakx-cluster-superuser
                key: password  
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: tools-keycloakx-cluster-superuser
                key: username
          - name: KC_DB_URL_PORT
            value: "5432" 
          - name: KC_DB_URL_HOST
            valueFrom:
              secretKeyRef:
                name: tools-keycloakx-cluster-superuser
                key: host 
          - name: KC_DB_URL_DATABASE
            value: keycloak    
        cache:
          stack: custom                                                                                          
        ingress:
          enabled: true
          servicePort: http
          annotations:
             nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
             nginx.ingress.kubernetes.io/proxy-body-size: 100m
             nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
             nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
             nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"         
          ingressClassName: public
          rules:
            -
              host: 'sso.dorsa.dev'
              paths:
                - path: '{{ "{{" }} tpl .Values.http.relativePath $ | trimSuffix "/" {{ "}}" }}/'
                  pathType: Prefix
          tls: 
            - hosts:
                - sso.dorsa.dev
              secretName: "sso-acme-issuer"
        
          console:
            enabled: true
            annotations:
               nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
               nginx.ingress.kubernetes.io/proxy-body-size: 100m
               nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
               nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
               nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"           
            ingressClassName: public
            rules:
              -
                host: 'sso.dorsa.dev'
                paths:
                  - path: '{{ "{{" }} tpl .Values.http.relativePath $ | trimSuffix "/" {{ "}}" }}/admin'
                    pathType: Prefix
            tls: 
              - hosts:
                  - sso.dorsa.dev
                secretName: "sso-acme-issuer"
        proxy:
           mode: xforwarded                
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"   

  - repoURL: 'https://cloudnative-pg.io/charts'
    targetRevision: 0.0.8
    chart: cluster
    helm:
      values: |-
        cluster:
          instances: 3
          annotations:
            cnpg.io/skipWalArchiving: "enabled"
          imageName: {{ .Values.spec.registry }}/cloudnative-pg/postgresql:16.1
          logLevel: warning
          storage:
            size: 5Gi
            storageClass: "local-sc"
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          initdb:
            database: keycloak
        backups:
          enabled: false

  - repoURL: '{{ .Values.spec.source.helmURL }}'
    targetRevision: "13.2.12"
    chart: app
    helm:
      values: |-
          fullnameOverride: postgresbackup
          global:
            imageRegistry: {{ .Values.spec.registry }}/
          image:
             repository: eeshugerman/postgres-backup-s3
             tag: 16
          extraEnvVars:
            - name: S3_ENDPOINT
              value: http://192.168.200.100:6000
            - name: SCHEDULE
              value:  '0 0 */6 * * *'
            - name: BACKUP_KEEP_DAYS
              value: "15"
            - name: S3_REGION
              value: "minio"
            - name: S3_ACCESS_KEY_ID
              value: "7Xsu50XzoQi91dLWCBQu2UOrb7ly9poh"
            - name: S3_SECRET_ACCESS_KEY
              value: "ZzbddQQSgDHrxWscxLI7PsLNTKoX4Wty"
            - name: S3_BUCKET
              value: "keycloakx"
            - name: S3_PREFIX
              value: "db"
            - name: POSTGRES_HOST
              valueFrom:
               secretKeyRef:
                 name: tools-keycloakx-cluster-superuser
                 key: host
            - name: POSTGRES_DATABASE
              value: keycloak
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tools-keycloakx-cluster-superuser
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tools-keycloakx-cluster-superuser
                  key: password           
          livenessProbe:
            enabled: false
          readinessProbe:
            enabled: false  
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 500Mi                                
          service:
            type: ClusterIP
