apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:      
  name: {{ .Values.spec.env }}-vector
  namespace: argocd
 
spec:
  destination:
    namespace: vector
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  syncPolicy:
   automated: {}
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan
    - ServerSideApply=true
  source:
    repoURL: 'https://helm.vector.dev'
    targetRevision: "0.49.0"
    chart: vector
    helm:
      values: |-
        role: "Agent"
        image:
          repository: {{ .Values.spec.registry }}/timberio/vector
        service:
          enabled: false  
        customConfig:
           data_dir: "/vector-data-dir"
           log_schema:
              timestamp_key: "@timestamp"
           sources:
             kubernetes:
                type: kubernetes_logs
           sinks:
             elastic:
              type: elasticsearch
              inputs:
                - removefields
              auth:
                strategy: basic
                user: elastic
                password: 97CpYis42iGZ4rAq7956wb0j  
              api_version: auto
              compression: none
              endpoints:
                - https://elastic-log.rimci.dev
              id_key: id
              mode: bulk
              bulk:
                action: create 
                index: logs-data-stream-tools-%Y-%m-%d 
           transforms:
             removefields:
               type: remap
               inputs:
                 - kubernetes
               source: |
                 del(.kubernetes.container_id)
                 del(.kubernetes.container_image_id)
                 del(.kubernetes.pod_name)
                 del(.kubernetes.pod_uid)
                 del(.kubernetes.pod_owner)
                 del(.kubernetes.pod_labels)
                 del(.kubernetes.pod_ips)
                 del(.kubernetes.pod_ip)
                 del(.kubernetes.pod_annotations)
                 del(.kubernetes.node_labels)
                 del(.kubernetes.namespace_labels)
                 del(.kubernetes.container_name)
                 del(.stream)
                 del(.source_type)
                 del(.file)