apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: arvancloud-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ali.eliasi@nak-mci.ir
    privateKeySecretRef:
      name: arvancloud-issuer-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.arvancloud.ir
          solverName: arvancloud
          config:
            apiKeySecretRef:
              name: arvancloud-api-key
              key: apikey
            ttl: 120